### ISSUE TITLE
Hnet-train problem

### ISSUE THREAD

**Issue by Philip035** [stesha2016/lanenet-enet-hnet#11]
Traceback (most recent call last):
  File "lanenet-enet-hnet/data_provider/hnet_data_processor.py", line 111, in next_batch
    return self.next_batch(batch_size)
  File "lanenet-enet-hnet/data_provider/hnet_data_processor.py", line 111, in next_batch
    return self.next_batch(batch_size)
  File "anenet-enet-hnet/data_provider/hnet_data_processor.py", line 111, in next_batch
    return self.next_batch(batch_size)
  [Previous line repeated 993 more times]
  File "lanenet-enet-hnet/data_provider/hnet_data_processor.py", line 109, in next_batch
    self._random_dataset()
  File "lanenet-enet-hnet/data_provider/hnet_data_processor.py", line 93, in _random_dataset
    random_idx = np.random.permutation(self._label_image_path.shape[0])
  File "mtrand.pyx", line 4887, in mtrand.RandomState.permutation
  File "mtrand.pyx", line 4821, in mtrand.RandomState.shuffle
RecursionError: maximum recursion depth exceeded in comparison
how should I fix it?

**Comment by RickXiang** [comment]
I have the same problem,have you sloved it?

**Comment by ghost** [comment]
also i get the same error anyone guys solve it?

**Comment by llyyccccc** [comment]
> I have the same problem,have you sloved it?

您好 您有tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000文件吗？ 能否发我一份？
