### ISSUE TITLE
TypeError: Scalar value for argument 'color' 

### ISSUE THREAD

**Issue by xuxiuzhi2627** [stesha2016/lanenet-enet-hnet#3]
how to sovle it?
Traceback (most recent call last):
  File "lanenet_hnet_predict.py", line 187, in <module>
    predict(args.image_path, args.lanenet_weights, args.hnet_weights)
  File "lanenet_hnet_predict.py", line 181, in predict
    mask_image = hnet_predict(image_hnet, hnet_weights, lanes_pts, image_vis)
  File "lanenet_hnet_predict.py", line 149, in hnet_predict
    cv2.circle(image, (coefficient_back[0][j], coefficient_back[1][j]), 1, (color[0], color[1], color[2]), 1)
TypeError: Scalar value for argument 'color' is not numeric

**Comment by xxzcxb1314** [comment]
Traceback (most recent call last):
  File "test_lanenet.py", line 258, in <module>
    save_dir=args.save_dir, use_gpu=args.use_gpu, batch_size=args.batch_size)
  File "test_lanenet.py", line 164, in test_lanenet_batch
    net = lanenet_merge_model.LaneNet(phase=phase_tensor, net_flag='vgg')
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/lanenet_model/lanenet_merge_model.py", line 42, in __init__
    self._decoder = fcn_decoder.FCNDecoder(phase=phase)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 28, in __init__
    self._is_training = self._init_phase()
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 35, in _init_phase
    return tf.equal(self._phase, self._train_phase)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2649, in equal
    "Equal", x=x, y=y, name=name)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Equal' Op has type bool that does not match type string of argument 'x'.
怎么解决呢？
