### ISSUE TITLE
python test_lanenet.py出错

### ISSUE THREAD

**Issue by xuxiuzhi2627** [stesha2016/lanenet-enet-hnet#4]
python test_lanenet.py --is_batch True --batch_size 2 --save_dir data/tusimple_test_image/ret  --weights_path model/tusimple_lanenet_enet/tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000 --image_path data/tusimple_test_image/
I0812 17:20:39.791164 24485 test_lanenet.py:156] 开始获取图像文件路径...
Traceback (most recent call last):
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 931, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype bool: 'Tensor("Const_3:0", shape=(), dtype=bool)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_lanenet.py", line 258, in <module>
    save_dir=args.save_dir, use_gpu=args.use_gpu, batch_size=args.batch_size)
  File "test_lanenet.py", line 164, in test_lanenet_batch
    net = lanenet_merge_model.LaneNet(phase=phase_tensor, net_flag='vgg')
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/lanenet_model/lanenet_merge_model.py", line 42, in __init__
    self._decoder = fcn_decoder.FCNDecoder(phase=phase)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 28, in __init__
    self._is_training = self._init_phase()
  File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 35, in _init_phase
    return tf.equal(self._phase, self._train_phase)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2649, in equal
    "Equal", x=x, y=y, name=name)
  File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Equal' Op has type bool that does not match type string of argument 'x'.

**Comment by PassionYezi** [comment]
Hello！Do you have tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000?Could you send me? Thanks!

**Comment by sdfsfszfzs** [comment]
I have the same question. I think it should be that the type of 'is_batch' goes wrong. Did u fix it ?

**Comment by EltonBraggs** [comment]
I am having the same issue.
Did  anyone find the solution?

**Comment by EltonBraggs** [comment]
> 
> 
> python test_lanenet.py --is_batch True --batch_size 2 --save_dir data/tusimple_test_image/ret --weights_path model/tusimple_lanenet_enet/tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000 --image_path data/tusimple_test_image/
> I0812 17:20:39.791164 24485 test_lanenet.py:156] 开始获取图像文件路径...
> Traceback (most recent call last):
> File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
> preferred_dtype=default_dtype)
> File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
> ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 931, in _TensorTensorConversionFunction
> (dtype.name, t.dtype.name, str(t)))
> ValueError: Tensor conversion requested dtype string for Tensor with dtype bool: 'Tensor("Const_3:0", shape=(), dtype=bool)'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "test_lanenet.py", line 258, in
> save_dir=args.save_dir, use_gpu=args.use_gpu, batch_size=args.batch_size)
> File "test_lanenet.py", line 164, in test_lanenet_batch
> net = lanenet_merge_model.LaneNet(phase=phase_tensor, net_flag='vgg')
> File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/lanenet_model/lanenet_merge_model.py", line 42, in **init**
> self._decoder = fcn_decoder.FCNDecoder(phase=phase)
> File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 28, in **init**
> self._is_training = self._init_phase()
> File "/home/xxz123456/anaconda3/envs/xxzproject/lanenet-enet-hnet-master/encoder_decoder_model/fcn_decoder.py", line 35, in _init_phase
> return tf.equal(self._phase, self._train_phase)
> File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2649, in equal
> "Equal", x=x, y=y, name=name)
> File "/home/xxz123456/anaconda3/envs/xxzproject/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
> inferred_from[input_arg.type_attr]))
> TypeError: Input 'y' of 'Equal' Op has type bool that does not match type string of argument 'x'.

I am getting the same issue. Have you found a soluion to this?

**Comment by llyyccccc** [comment]
> Hello！Do you have tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000?Could you send me? Thanks!

您好  您有权重文件了吗？ 如果有的话可否发我一份
