### ISSUE TITLE
An error occurred when I run "lanenet_hnet_predict.py"

### ISSUE THREAD

**Issue by zwb204** [stesha2016/lanenet-enet-hnet#6]
Traceback (most recent call last):
  File "lanenet_hnet_predict.py", line 177, in <module>
    predict(args.image_path, args.lanenet_weights, args.hnet_weights)
  File "lanenet_hnet_predict.py", line 171, in predict
    mask_image = hnet_predict(image_hnet, hnet_weights, lanes_pts, image_vis)
  File "lanenet_hnet_predict.py", line 139, in hnet_predict
    cv2.circle(image, (coefficient_back[0][j], coefficient_back[1][j]), 1, (color[0], color[1], color[2]), 1)
TypeError: Scalar value for argument 'color' is not numeric

**Comment by ashergaga** [comment]
@zwb204 Hi, I met the same problem with you ,have you solved it?

**Comment by zwb204** [comment]
> @zwb204 Hi, I met the same problem with you ,have you solved it?

cv2.circle(image, (int(coefficient_back[0][j]), int(coefficient_back[1][j])), 1, (int(color[0]), int(color[1]), int(color[2])), 1)

**Comment by zwb204** [comment]
@ashergaga 
cv2.circle(image, (int(coefficient_back[0][j]), int(coefficient_back[1][j])), 1, (int(color[0]), int(color[1]), int(color[2])), 1)
